name: workflowCD

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  job-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Setando conexao SSH do Google Cloud
        run: |
          mkdir -p ~/.ssh/	
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GOOGLE_CLOUD_USER }}
          SSH_KEY: ${{ secrets.GOOGLE_CLOUD_SSH }}
          SSH_HOST: ${{ secrets.GOOGLE_CLOUD_IP }}
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtendo nodejs 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
        
      - name: Instalando dependencias
        run: |
          npm install
          
      - name: Testandop
        run: |
          npm run test -- --coverage
        env:
          CI: true
      
      - name: Fazendo Build
        run: |
          npm run build
      
      - name: Fazendo Deploy
        run: |
          ssh google-cloud 'sudo systemctl stop exercicioworkflow'
          ssh google-cloud 'sudo rm -rf /app/react-app'
          scp -r build google-cloud:/app/react-app
          ssh google-cloud 'sudo mv /home/github/react-app /app/react-app'
          ssh google-cloud 'sudo systemctl start exercicioworkflow'
      
      - name: Uso do SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
