name: workflowCI

on:
  push:
    branches:
      - feature-new
  pull_request:
    branches:
      - feature-new
  workflow_dispatch:
  
defaults:
  run:
    working-directory: frontend/gmusic/

jobs:
  job-CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Obtendo nodejs 16
      uses: actions/setup-node@v3
      with: 
        node-version: 16.x

    - name: Instalando dependencias
      run: npm install
      
    - name: Fazendo build
      run: npm run build
      
      env:
        CI: true
    
    - name: Uso do SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}