name: workflowCI

on:
  push:
    branches:
      - feature-new
  workflow_dispatch:

jobs:
  job-CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build pagina/ -t $DOCKER_USER/atividadehtml:latest
          docker push $DOCKER_USER/atividadehtml:latest
